# Generated by Django 5.0.1 on 2026-06-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('medical_upload', 'Medical Upload'), ('medical_under_review', 'Medical Under Review'), ('medical_info_requested', 'Medical Info Requested'), ('medical_resubmission', 'Medical Resubmission'), ('medical_rejected', 'Medical Rejected'), ('pre_onboarding', 'Pre-Onboarding'), ('pre_onboarding_submitted', 'Pre-Onboarding Submitted'), ('pre_onboarding_resubmission', 'Pre-Onboarding Resubmission'), ('pre_onboarding_info_requested', 'Pre-Onboarding Info Requested'), ('pre_onboarding_rejected', 'Pre-Onboarding Rejected'), ('onboarding', 'Onboarding'), ('onboarding_submitted', 'Onboarding Submitted'), ('onboarding_resubmission', 'Onboarding Resubmission'), ('onboarding_info_requested', 'Onboarding Info Requested'), ('onboarding_rejected', 'Onboarding Rejected'), ('post_onboarding', 'Post-Onboarding'), ('post_onboarding_submitted', 'Post-Onboarding Submitted'), ('post_onboarding_resubmission', 'Post-Onboarding Resubmission'), ('post_onboarding_info_requested', 'Post-Onboarding Info Requested'), ('post_onboarding_rejected', 'Post-Onboarding Rejected'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='pending', max_length=40),
        ),
    ]
