# Generated by Django 5.0.1 on 2026-06-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
