# Generated by Django 5.0.1 on 2026-06-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_medicalrecord_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgunit',
            name='kind',
            field=models.CharField(choices=[('department', 'Department'), ('designation', 'Designation'), ('location', 'Location'), ('grade', 'Grade'), ('payroll', 'Payroll'), ('employee_type', 'Employee Type')], default='department', max_length=30),
        ),
    ]
