# Generated by Django 5.0.1 on 2026-06-14 20:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_orgunit_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('kind', models.CharField(choices=[('message', 'Message'), ('info_request', 'Information Request'), ('changes', 'Changes Requested'), ('rejection', 'Rejection'), ('reply', 'Employee Reply')], default='message', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_review_messages', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review_message',
                'ordering': ['created_at'],
            },
        ),
    ]
