# Generated by Django 5.0.1 on 2026-06-14 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_goal_manager_remove_goal_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmessage',
            name='medical_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.medicalrecord'),
        ),
        migrations.AddField(
            model_name='user',
            name='scope',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
