# Generated by Django 5.0.1 on 2026-06-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reviewmessage_medical_record_user_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='kind',
            field=models.CharField(choices=[('knowledge', 'Knowledge Article'), ('training', 'Training Module'), ('orientation', 'Orientation Session'), ('presentation', 'Presentation'), ('portal_slider', 'Portal Slider'), ('portal_gallery', 'Portal Gallery'), ('portal_video', 'Portal Video'), ('portal_resource', 'Portal Resource'), ('management_message', 'Management Message')], db_index=True, max_length=30),
        ),
    ]
