# Generated by Django 5.0.1 on 2026-06-18 08:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_medicalrecord_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_key', models.CharField(choices=[('medical', 'Medical Clearance'), ('pre_onboarding', 'Pre-Onboarding'), ('onboarding', 'Onboarding'), ('post_onboarding', 'Post-Onboarding')], db_index=True, help_text="System identifier for this stage (e.g., 'medical')", max_length=50, unique=True)),
                ('label', models.CharField(help_text="Display name for this stage (e.g., 'Medical Clearance')", max_length=100)),
                ('default_due_date_days', models.IntegerField(default=7, help_text='Default deadline in days from start of stage')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this stage is active in the onboarding flow')),
                ('order', models.IntegerField(db_index=True, default=0, help_text='Position in onboarding pipeline (0-first, 3-last)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Onboarding Stage',
                'verbose_name_plural': 'Onboarding Stages',
                'db_table': 'stage',
                'ordering': ['order'],
            },
        ),
    ]
