# Generated by Django 5.0.1 on 2026-06-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_stage_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stage_due_date',
            field=models.DateTimeField(blank=True, help_text='Calculated due date for current stage (based on Stage.default_due_date_days)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stage_due_date_override',
            field=models.DateTimeField(blank=True, help_text='If set, overrides the calculated due date (HR can customize per employee)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stage_entered_at',
            field=models.DateTimeField(blank=True, help_text='When employee entered their current stage', null=True),
        ),
    ]
