# Generated by Django 5.0.1 on 2026-06-18 10:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_stage_due_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('7d_before', '7 days before'), ('3d_before', '3 days before'), ('1d_before', '1 day before'), ('day_of', 'Day of deadline')], max_length=20)),
                ('scheduled_date', models.DateTimeField(help_text='When the reminder should be sent')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reminder',
                'indexes': [models.Index(fields=['status', 'scheduled_date'], name='reminder_status_c531df_idx'), models.Index(fields=['employee', 'status'], name='reminder_employe_d13f70_idx')],
                'unique_together': {('employee', 'reminder_type', 'scheduled_date')},
            },
        ),
    ]
