# Generated by Django 5.0.1 on 2026-06-21 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_notification_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeStagePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stages', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('change_reason', models.TextField(blank=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_stage_path', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_stage_path',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='stage_path',
            field=models.OneToOneField(blank=True, help_text='If set, employee follows this custom stage path. Otherwise uses global defaults.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.employeestagepath'),
        ),
        migrations.CreateModel(
            name='StageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('stages', models.JSONField(blank=True, default=list)),
                ('is_global', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stage_template',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OfferWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_number', models.CharField(max_length=50, unique=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('signed', 'Signed - Pending Acceptance'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_by_name', models.CharField(blank=True, max_length=100)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('offer_data', models.JSONField(default=dict)),
                ('expiry_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
                ('offer_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.form')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offer_workflow',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='offer_workf_employe_308df0_idx'), models.Index(fields=['sent_by'], name='offer_workf_sent_by_404e71_idx')],
            },
        ),
        migrations.CreateModel(
            name='StageDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('default_due_date_days', models.IntegerField(default=7)),
                ('approval_role', models.CharField(blank=True, max_length=50)),
                ('stage_type', models.CharField(choices=[('mandatory', 'Mandatory - all employees'), ('optional', 'Optional - depends on employee type/role'), ('conditional', 'Conditional - based on organization/department')], default='mandatory', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stage_definition',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['stage_key'], name='stage_defin_stage_k_847ef7_idx'), models.Index(fields=['is_enabled'], name='stage_defin_is_enab_fde0b2_idx')],
            },
        ),
    ]
