from django.urls import path

from .views import (auth_views, employee_views, admin_views, public_views,
                    common_views, content_views, training_views, analytics_views, signature_views,
                    assessment_views, session_views, onboarding_plan_views, chat_views, zoom_settings_views,
                    stage_config_views, quiz_views, offer_views, offer_api_views, public_offer_views, buddy_views)

urlpatterns = [
    # ── Public / dispatch ───────────────────────────────────────────────
    path("", common_views.index, name="index"),
    path("portal/", common_views.portal, name="portal"),

    # ── Auth ────────────────────────────────────────────────────────────
    path("login/", auth_views.login_view, name="login"),
    path("login/staff/", auth_views.staff_login_view, name="staff_login"),
    path("logout/", auth_views.logout_view, name="logout"),
    path("forgot-password/", auth_views.forgot_password, name="forgot_password"),
    path("reset-password/<str:token>/", auth_views.reset_password, name="reset_password"),
    path("change-password/", auth_views.change_password, name="change_password"),
    path("profile/", auth_views.profile, name="profile"),
    path("activate/<str:token>/", auth_views.activate, name="activate"),

    # ── Employee ────────────────────────────────────────────────────────
    path("employee/home/", employee_views.home, name="employee_home"),
    path("employee/set-joining-date/", employee_views.set_joining_date, name="employee_set_joining_date"),
    path("employee/medical/", employee_views.medical, name="employee_medical"),
    path("employee/pre-onboarding/", employee_views.pre_onboarding, name="employee_pre_onboarding"),
    path("employee/onboarding/", employee_views.onboarding, name="employee_onboarding"),
    path("employee/post-onboarding/", employee_views.post_onboarding, name="employee_post_onboarding"),
    path("employee/on-hold/", employee_views.on_hold, name="employee_on_hold"),
    path("employee/form/<int:form_id>/", employee_views.fill_form, name="fill_form"),

    # ── Admin ───────────────────────────────────────────────────────────
    path("admin/dashboard/", admin_views.dashboard, name="admin_dashboard"),
    path("admin/analytics/", analytics_views.analytics_dashboard, name="admin_analytics"),
    path("admin/analytics/training/", analytics_views.training_analytics, name="admin_analytics_training"),
    path("admin/analytics/sessions/", analytics_views.session_analytics, name="admin_analytics_sessions"),
    path("admin/analytics/export/<str:report_type>/", analytics_views.export_analytics_csv, name="admin_analytics_export"),
    path("admin/employees/", admin_views.employees, name="admin_employees"),
    path("admin/employees/export/", admin_views.export_employees, name="admin_export_employees"),
    path("admin/employees/import/", admin_views.import_employees, name="admin_import_employees"),
    path("admin/employees/<int:user_id>/upload-on-behalf/", admin_views.upload_on_behalf, name="admin_upload_on_behalf"),
    path("admin/users/export/", admin_views.export_users, name="admin_export_users"),
    path("admin/employees/<int:user_id>/export/", admin_views.export_employee_detail, name="admin_export_employee_detail"),
    path("admin/employees/<int:user_id>/export-package/", admin_views.export_employee_package, name="admin_export_employee_package"),
    path("admin/users/<int:user_id>/reset-password/", admin_views.reset_user_password, name="admin_reset_user_password"),
    path("admin/forms/<int:form_id>/responses/export/", admin_views.export_form_responses_view, name="admin_export_form_responses"),
    path("admin/employees/<int:user_id>/", admin_views.employee_detail, name="admin_employee_detail"),
    path("admin/employees/<int:user_id>/review/", admin_views.review_employee, name="admin_review_employee"),
    path("admin/employees/<int:user_id>/bypass-stage/", admin_views.bypass_stage, name="admin_bypass_stage"),
    path("admin/employees/<int:user_id>/bypass-all/", admin_views.bypass_all_stages, name="admin_bypass_all"),
    path("admin/employees/<int:user_id>/message/", admin_views.message_employee, name="admin_message_employee"),
    path("admin/employees/bulk-delete/", admin_views.bulk_delete_employees, name="admin_bulk_delete_employees"),
    path("admin/employees/<int:user_id>/delete/", admin_views.delete_employee, name="admin_delete_employee"),
    path("admin/users/", admin_views.users, name="admin_users"),
    path("admin/users/bulk-delete/", admin_views.bulk_delete_users, name="admin_bulk_delete_users"),
    path("admin/users/create/", admin_views.create_user, name="admin_create_user"),
    path("admin/users/<int:user_id>/edit/", admin_views.edit_user, name="admin_edit_user"),
    path("admin/users/<int:user_id>/delete/", admin_views.delete_user, name="admin_delete_user"),
    path("admin/offers/", admin_views.offers, name="admin_offers"),
    path("admin/offers/send/", admin_views.send_offer, name="admin_send_offer"),
    path("admin/offers/<int:offer_id>/resend/", admin_views.resend_offer, name="admin_resend_offer"),
    path("admin/offers/analytics/", offer_api_views.offer_analytics, name="admin_offers_analytics"),
    path("admin/offers/analytics/view/", admin_views.offers_analytics_page, name="admin_offers_analytics_page"),
    path("admin/offers/export/", offer_api_views.export_offers_csv, name="admin_offers_export"),
    path("employee/offers/", offer_views.my_offers, name="my_offers"),
    path("employee/offers/<int:offer_id>/respond/", offer_views.respond_to_offer, name="respond_to_offer"),
    # Public offer token-based views
    path("offers/view/<str:token>/", public_offer_views.public_offer_view, name="public_offer_view"),
    path("offers/<str:token>/accept/", public_offer_views.public_offer_accept, name="public_offer_accept"),
    path("offers/<str:token>/reject/", public_offer_views.public_offer_reject, name="public_offer_reject"),
    # Offer API endpoints (templates & email templates)
    path("api/offers/templates/", offer_api_views.offer_templates_list, name="api_offer_templates"),
    path("api/offers/templates/<int:template_id>/", offer_api_views.offer_template_detail, name="api_offer_template_detail"),
    path("api/offers/email-templates/", offer_api_views.email_templates_list, name="api_offer_email_templates"),
    path("api/offers/email-templates/<int:template_id>/", offer_api_views.email_template_detail, name="api_offer_email_template_detail"),
    path("api/offers/email-template-choices/", offer_api_views.offer_email_template_choices, name="api_offer_email_template_choices"),
    path("api/offers/", offer_api_views.offers_list, name="api_offers"),
    path("api/offers/<int:offer_id>/", offer_api_views.offer_detail, name="api_offer_detail"),
    path("api/offers/preview/", offer_api_views.offer_render_preview, name="api_offer_render_preview"),
    path("api/offers/<int:offer_id>/preview/", offer_api_views.offer_render_preview, name="api_offer_render_preview_offer"),
    path("api/offers/<int:offer_id>/snapshot/", offer_api_views.offer_snapshot_send, name="api_offer_snapshot_send"),
    path("api/offers/<int:offer_id>/approvals/<int:approval_id>/approve/", offer_api_views.approve_offer_approval, name="api_offer_approval_approve"),
    path("api/offers/<int:offer_id>/approvals/<int:approval_id>/reject/", offer_api_views.reject_offer_approval, name="api_offer_approval_reject"),
    path("api/offers/<int:offer_id>/approvals/", offer_api_views.offer_approvals_list, name="api_offer_approvals_list"),
    path("api/offers/<int:offer_id>/approvals/<int:approval_id>/", offer_api_views.offer_approval_detail, name="api_offer_approval_detail"),
    path("api/offers/fields/", offer_api_views.offer_fields_list, name="api_offer_fields"),
    path("api/offers/fields/<int:field_id>/", offer_api_views.offer_field_detail, name="api_offer_field_detail"),
    path("api/offers/uploads/image/", offer_api_views.offer_image_upload, name="api_offer_image_upload"),
    path("api/offers/templates/<int:template_id>/preview/", offer_api_views.offer_template_preview, name="api_offer_template_preview"),
    path("api/offers/<int:offer_id>/pdf/", offer_api_views.offer_pdf_export_api_view, name="api_offer_pdf_export"),
    path("admin/offers/<int:offer_id>/pdf/", admin_views.admin_offer_pdf_export, name="admin_offer_pdf_export"),
    path("admin/offers/export/zip/", admin_views.offers_bulk_zip_export_view, name="admin_offers_bulk_zip_export"),
    path("admin/forms/", admin_views.forms_list, name="admin_forms"),
    path("admin/forms/create/", admin_views.create_form, name="admin_create_form"),
    path("admin/forms/<int:form_id>/edit/", admin_views.edit_form, name="admin_edit_form"),
    path("admin/forms/<int:form_id>/analytics/", admin_views.form_analytics_view, name="admin_form_analytics"),
    path("admin/forms/<int:form_id>/toggle/", admin_views.toggle_form_active, name="admin_toggle_form"),
    path("admin/forms/<int:form_id>/delete/", admin_views.delete_form, name="admin_delete_form"),
    path("admin/documents/", admin_views.onboarding_documents, name="admin_onboarding_documents"),
    path("admin/medical-requirements/", admin_views.medical_requirements, name="admin_medical_requirements"),
    path("admin/organization/", admin_views.organization, name="admin_organization"),
    path("admin/landing/", admin_views.portal_cms, name="admin_portal_cms"),
    path("admin/roles/", admin_views.roles, name="admin_roles"),
    path("admin/medical/review/", admin_views.medical_review, name="admin_medical_review"),
    path("admin/medical/review/export/", admin_views.export_medical_documents, name="admin_export_medical"),
    path("admin/medical/review/export-csv/", admin_views.export_medical_stats_csv, name="admin_export_medical_stats_csv"),
    path("admin/settings/email/", admin_views.email_settings, name="admin_email_settings"),
    path("admin/settings/email-templates/", admin_views.email_templates, name="admin_email_templates"),
    path("admin/settings/email-logs/", admin_views.email_logs, name="admin_email_logs"),
    path("admin/settings/email-statistics/", admin_views.email_statistics, name="admin_email_statistics"),
    path("admin/settings/offer-templates/", admin_views.offer_templates_manage, name="admin_offer_templates"),
    path("admin/settings/offer-templates/<int:template_id>/delete/", admin_views.offer_template_delete, name="admin_offer_template_delete"),
    path("admin/settings/offer-email-templates/", admin_views.offer_email_templates_manage, name="admin_offer_email_templates"),
    path("admin/settings/offer-email-templates/<int:template_id>/delete/", admin_views.offer_email_template_delete, name="admin_offer_email_template_delete"),
    path("admin/settings/reset/", admin_views.portal_reset, name="admin_portal_reset"),
    path("admin/settings/zoom/", zoom_settings_views.zoom_settings, name="zoom_settings"),
    path("admin/automation/", admin_views.automation, name="admin_automation"),
    path("settings/notifications/", auth_views.notification_preferences, name="notification_preferences"),
    path("admin/branding/", admin_views.branding, name="admin_branding"),

    # ── Setup: Stages & Workflow Templates ──────────────────────────────────────
    path("admin/setup/stages/", stage_config_views.stages_list, name="admin_stages_list"),
    path("admin/setup/stages/create/", stage_config_views.stage_create, name="admin_stage_create"),
    path("admin/setup/stages/<int:stage_id>/edit/", stage_config_views.stage_edit, name="admin_stage_edit"),
    path("admin/setup/templates/", stage_config_views.templates_list, name="admin_templates_list"),
    path("admin/setup/templates/create/", stage_config_views.template_create, name="admin_template_create"),
    path("admin/setup/templates/<int:template_id>/edit/", stage_config_views.template_edit, name="admin_template_edit"),
    path("admin/setup/templates/<int:template_id>/delete/", stage_config_views.template_delete, name="admin_template_delete"),
    path("admin/setup/templates/<int:template_id>/set-default/", stage_config_views.template_set_default, name="admin_template_set_default"),

    # ── Live Sessions ────────────────────────────────────────────────────────────
    path("sessions/", session_views.sessions_dashboard, name="sessions_dashboard"),
    path("sessions/create/", session_views.create_session, name="create_session"),
    path("sessions/<int:session_id>/", session_views.session_detail, name="session_detail"),
    path("sessions/<int:session_id>/register/", session_views.register_session, name="register_session"),
    path("sessions/<int:session_id>/approve-attendee/<int:attendee_id>/", session_views.approve_attendee, name="approve_attendee"),
    path("sessions/<int:session_id>/approve/", session_views.approve_session, name="approve_session"),
    path("sessions/<int:session_id>/mark-attendance/", session_views.mark_attendance, name="session_mark_attendance"),
    path("sessions/<int:session_id>/feedback/", session_views.session_feedback, name="session_feedback"),

    # ── Assessments & Courses ────────────────────────────────────────────────────
    path("course/<int:course_id>/lessons/", assessment_views.course_lessons, name="course_lessons"),
    path("course/<int:course_id>/lesson/<str:lesson_id>/", assessment_views.lesson_detail, name="lesson_detail"),
    path("course/<int:course_id>/lesson/<str:lesson_id>/quiz/", assessment_views.take_quiz, name="take_quiz"),
    path("course/<int:course_id>/lesson/<str:lesson_id>/submit/", assessment_views.submit_quiz, name="submit_quiz"),
    path("course/<int:course_id>/lesson/<str:lesson_id>/results/", assessment_views.quiz_results, name="quiz_results"),
    path("course/<int:course_id>/progress/", assessment_views.course_progress, name="course_progress"),
    path("course/<int:course_id>/lesson/<str:lesson_id>/video-position/", assessment_views.save_video_position, name="save_video_position"),

    # ── Notifications & Documents ───────────────────────────────────────────────────
    path("document/<int:doc_id>/", common_views.document_view, name="document_view"),
    path("document/<int:doc_id>/sign/", signature_views.document_sign_page, name="document_sign"),
    path("signature/create/", signature_views.create_signature, name="create_signature"),
    path("signature/<uuid:sig_id>/", signature_views.view_signature, name="view_signature"),
    path("signature/<uuid:sig_id>/verify/", signature_views.verify_signature, name="verify_signature"),
    path("signature/<uuid:sig_id>/download/", signature_views.download_signature, name="download_signature"),
    path("notifications/", common_views.notifications_list, name="notifications_list"),
    path("notifications/feed/", common_views.notifications_feed, name="notifications_feed"),
    path("notifications/<int:notif_id>/read/", common_views.notification_mark_read, name="notification_mark_read"),
    path("notifications/mark-all-read/", common_views.notifications_mark_all_read, name="notifications_mark_all_read"),
    path("notifications/clear/", common_views.notifications_clear, name="notifications_clear"),

    # ── Training & Learning Paths (specific routes before generic learn/<kind>) ──
    path("admin/training/paths/", training_views.learning_paths, name="admin_learning_paths"),
    path("admin/training/paths/<int:pk>/edit/", training_views.learning_path_edit, name="admin_learning_path_edit"),
    path("admin/training/paths/<int:pk>/analytics/", training_views.learning_path_analytics_view, name="admin_learning_path_analytics"),
    path("admin/training/assignments/", training_views.training_assignments, name="admin_training_assignments"),
    path("learn/my-learning/", training_views.my_learning, name="my_learning"),
    path("learn/path/<int:pk>/", training_views.learning_path_detail, name="learning_path_detail"),
    path("learn/path/<int:pk>/certificate/", training_views.learning_certificate, name="learning_certificate"),

    # ── 30/60/90 Onboarding Plans ──
    path("employee/onboarding-plan/", onboarding_plan_views.my_onboarding_plan, name="my_onboarding_plan"),
    path("employee/onboarding-plan/milestone/complete/", onboarding_plan_views.mark_milestone_complete, name="mark_milestone_complete"),
    path("employee/onboarding-plan/<str:phase>/post/", onboarding_plan_views.post_plan_update, name="post_plan_update"),
    path("admin/onboarding-plans/", onboarding_plan_views.manage_onboarding_plans, name="manage_onboarding_plans"),
    path("admin/onboarding-plans/<int:employee_id>/", onboarding_plan_views.employee_plan_detail, name="employee_plan_detail"),
    path("admin/onboarding-plans/<int:employee_id>/milestone/update/", onboarding_plan_views.manager_mark_milestone, name="manager_mark_milestone"),
    path("admin/onboarding-plans/<int:employee_id>/feedback/", onboarding_plan_views.manager_post_feedback, name="manager_post_feedback"),

    # ── Real-time Chat & Messaging ──
    path("messages/", chat_views.messages_list, name="messages_list"),
    path("messages/<int:user_id>/", chat_views.chat_with_user, name="chat_with_user"),
    path("messages/<int:user_id>/read/", chat_views.mark_conversation_read, name="mark_conversation_read"),
    path("messages/chat/<int:chat_id>/accept/", chat_views.accept_chat_request, name="accept_chat_request"),
    path("messages/chat/<int:chat_id>/reject/", chat_views.reject_chat_request, name="reject_chat_request"),
    path("messages/chat/<int:chat_id>/delete/", chat_views.delete_chat_view, name="delete_chat"),
    path("messages/settings/", chat_views.chat_settings, name="chat_settings"),
    path("api/users/search/", chat_views.search_users_for_chat, name="search_users"),
    path("api/messages/unread/", chat_views.get_unread_count_view, name="get_unread_count"),

    # ── Content modules (knowledge / training / orientation / presentations) ──
    path("admin/content/<str:kind>/", content_views.manage, name="content_manage"),
    path("learn/<str:kind>/", content_views.browse, name="content_list"),
    path("learn/item/<int:item_id>/", content_views.read, name="content_read"),
    path("learn/orientation/<int:item_id>/ics/", content_views.orientation_ics_export, name="orientation_ics_export"),

    # ── Buddy / Mentorship Program ──
    path("admin/buddy-program/", buddy_views.admin_buddy_program, name="admin_buddy_program"),
    path("employee/buddy/", buddy_views.employee_buddy_dashboard, name="employee_buddy_dashboard"),
    path("buddy/plan/propose/", buddy_views.propose_buddy_plan, name="propose_buddy_plan"),
    path("buddy/milestone/signoff/", buddy_views.signoff_buddy_milestone, name="signoff_buddy_milestone"),
    path("buddy/checkin/log/", buddy_views.signoff_buddy_milestone, name="log_buddy_checkin"),

    # ── Public forms ────────────────────────────────────────────────────
    path("public/form/<str:token>/", public_views.public_form, name="public_form_view"),
    path("public/thank-you/", public_views.thank_you, name="public_thank_you"),

    # ── Quiz module ──────────────────────────────────────────────────────
    # Admin

    path("admin/quizzes/<int:quiz_id>/responses/", quiz_views.quiz_responses, name="quiz_responses"),
    path("admin/quizzes/<int:quiz_id>/preview/", quiz_views.quiz_preview, name="quiz_preview"),
    # Employee
    path("quiz/", quiz_views.my_quizzes, name="my_quizzes"),
    path("quiz/<int:quiz_id>/take/", quiz_views.take_quiz, name="take_quiz_standalone"),
    path("quiz/<int:quiz_id>/result/<int:response_id>/", quiz_views.quiz_result, name="quiz_result"),
]
